### ISSUE TITLE
Backlog limit has no effect

### ISSUE THREAD

**Issue by mikkel-ol** [mikkel-ol/I4IKN#1]
It seems the limit of the backlog queue on the file server has no effect on the number of concurrent 
clients. The file server needs to limit concurrent users to 1.

https://github.com/mikkel-ol/I4IKN/blob/9538834362ec7745b2968515ebda0e61d07b7f5e/exercise6/file_server/file_server.cs#L13

https://github.com/mikkel-ol/I4IKN/blob/9538834362ec7745b2968515ebda0e61d07b7f5e/exercise6/file_server/file_server.cs#L35

**Comment by mikkel-ol** [comment]
I have tried [this example](https://stackoverflow.com/questions/4253454/question-about-listening-and-backlog-for-sockets) given by user _ifs_ and I cannot limit the number of concurrent users.

@Suuren and @nikje94 - will you try and replicate the issue?

**Comment by n1dre** [comment]
>Note that this is concerned with peaks in concurrent connection attempts and in no way related to the maximum number of concurrent connections that your server can maintain. _(from best answer)_

Are you sure this is the way it should be done?

**Comment by Suuren** [comment]
Interessant, ja umiddelbart er der, jeg husker vagt noget fra ikn, at der også er en router queue. (så også på den server vi lejer) hvor de request bliver droppet, hvis den bliver fyldt.

Det er helt sikkert en fin idé at have en backlog queue, men skal det så ske i form af log ind?

Jeg studerer lige artiklen nærmere senere 😊
Kan du specificerer mere hvad jeg skal prøve af?

Edit: det kunne eventuelt laves som en admin function, som en red alert, hvor vi kan blokere brugere for adgang.

**Comment by n1dre** [comment]
@mikkel-ol Did you try setting `MAXCONN` to 0?

P.s. Why we speak the English?

**Comment by mikkel-ol** [comment]
@nikje94 I bemærkede not even that..

Yes, `MAXCONN` er blevet sat til 0, no effect.

@Suuren Om du er i stand til at begrænse antal connections på Windows - jeg læste noget om platformsrelevans.

**Comment by n1dre** [comment]
Alright. Please provide os med steps til replicate the issue. 

![https://tenor.com/xYSm.gif](https://media1.tenor.com/images/3525acc34c082fd463ba5e14b0e2e4b2/tenor.gif?itemid=5676484)

**Comment by mikkel-ol** [comment]
[Commit 9538834](https://github.com/mikkel-ol/I4IKN/commit/9538834362ec7745b2968515ebda0e61d07b7f5e) fra referencen indeholder allerede en (simpel) test.
